### ISSUE TITLE
MediaPlayerDevice is deprecated

### ISSUE THREAD

**Issue by iptvcld** [JeffLIrion/ha-androidtv#9]
On latest HA version

Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:938
Integration: Media player (documentation, issues)
First occurred: 10:37:13 PM (4 occurrences)
Last logged: 10:37:14 PM

MediaPlayerDevice is deprecated, modify ADBDevice to extend MediaPlayerEntity
MediaPlayerDevice is deprecated, modify AndroidTVDevice to extend MediaPlayerEntity
MediaPlayerDevice is deprecated, modify FireTVDevice to extend MediaPlayerEntity
MediaPlayerDevice is deprecated, modify BrowserModPlayer to extend MediaPlayerEntity

**Comment by JeffLIrion** [comment]
Fixed via https://github.com/JeffLIrion/ha-androidtv/commit/2af316a3900373cbe4158f250c953056b4d364d1

**Comment by iptvcld** [comment]
Updated to: 2af316a

But still getting
Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:938
Integration: Media player (documentation, issues)
First occurred: 2:22:16 AM (1 occurrences)
Last logged: 2:22:16 AM

MediaPlayerDevice is deprecated, modify BrowserModPlayer to extend MediaPlayerEntity
